# -*- coding: utf-8 -*-
"""student_performance_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aKRRKzNuoUby6DCovEafIuQZnttY1kyj

El rendimiento académico de los estudiantes es un fenómeno influenciado por múltiples factores vinculados tanto al contexto familiar como al comportamiento individual. Comprender qué variables impactan con mayor fuerza en los resultados permite orientar estrategias educativas más efectivas.

En este proyecto se analiza un conjunto de datos sobre desempeño estudiantil con el objetivo de identificar qué factores explican el puntaje final de los alumnos (Exam_Score). A través de un análisis exploratorio de datos (EDA), se estudian variables como la asistencia a clases, las horas de estudio, el nivel educativo de los padres, el desempeño previo y las horas de sueño.

Posteriormente, se evalúan las relaciones entre estas variables mediante visualizaciones, métricas estadísticas y pruebas de hipótesis, para finalmente construir un modelo predictivo basado en regresión lineal que permita estimar el rendimiento académico a partir de características observables del estudiante.

El objetivo principal es no solo describir los datos, sino también extraer conclusiones interpretables y construir una herramienta básica de predicción que evidencie cuáles son los factores con mayor impacto en el desempeño escolar.
"""

import kagglehub
import pandas as pd
import os
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as stats

# Download latest version
path = kagglehub.dataset_download("lainguyn123/student-performance-factors")

print("Path to dataset files:", path)

print(os.listdir(path))
file_path = path + "/StudentPerformanceFactors.csv"
df = pd.read_csv(file_path)
df.head() #primeras filas
df.shape #cantidad de filas y columnas

df

df.info() #estructura y ipo de datos

df.describe()

df.columns #nombres de columnas

df.isnull().sum() #valores nulos

df["Hours_Studied"].hist()

"""# **Limpieza del dataset**"""

df_clean = df.copy() #copia de seguridad

df_clean.isnull().sum()  #detecto los nulos por columna

"""teacher_quality 78 nulos parental_education_level = 90 nulos  distance_from_home 67 nulos. Para lo que quiero averiguar teacher quality no es importante. parental eduaction si, es una de las variables a analizar"""

mode_pe = df["Parental_Education_Level"].mode().iloc[0]         #pe es variable categoria por lo que no se puede usar media.
print(mode_pe)                                                  # fillna me reemplaza los nulos por la moda.
                                                                #iloc lo uso para acceder al indice es el lugar 0 lo que mas se repite
                                                                #y corresponde a high school

df_clean["Parental_Education_Level"].fillna(mode_pe, inplace= True)

df_clean.dropna(inplace= True)  #borro los datos nulos de las columnas que no me sirven

df_clean["Exam_Score"] = pd.to_numeric(df_clean["Exam_Score"], errors="coerce") #convierto todo a numeros
df_clean["Exam_Score"].isna().sum()  #isna= marca los nulos como true y el sum cuenta los true

df_clean.describe()

df_clean.boxplot(column="Exam_Score")

df_clean[df_clean["Exam_Score"] == 101]

"""Analizando la columnas de Exam_Scores vemos que tenemos cerca del 50% concentrado entre 65 y 67. Hay bastantes outliers y un caso particular donde el Score es de 101, suponiendo que la maxima nota es de 100, existe una discrepancia que puede ser entendida como que obtuvo un bonus, analizando las notas previas, las horas de estudio y la asistencia a clase tiene sentido que haya tenido una nota maxima y algun bonus. La presencia de outliers nos indica que la mayoria ronda los 67 puntos pero existen casos en donde desaprueban o son sobresalientes, cuestiones comunes en una escuela"""

df_clean.to_csv("estudiantes_limpio.csv", index=False)

df = pd.read_csv("estudiantes_limpio.csv")

"""La variable objetivo es Exam_Score porque el objetivo es ver como diversos factores impactan en el rendimiento escolar del alumno."""

df["Exam_Score"].describe()

"""Como analizamos anteriormente los valores rondan en un 67,25. Los datos estan concentrados y no existe mucha dispersion solo 3,90."""

df["Exam_Score"].hist(bins=20)
plt.show()

df["Exam_Score"].skew() #coeficiente de asimetría

"""La variable es asimetrica positiva: la mayoria de los valores se concentran a la izquierda de la distribución, con una cola hacia la derecha donde se ubican los valores mas altos. Además los resultados se agrupan cerca de la media y se observan valores extremos.
El coeficiente de asimetría obtenido es positivo, lo que confirma que la distribución presenta una cola hacia los valores más altos.

Influye el nivel academico de los padres en el rendimiento del estidiante?
"""

df_clean["Parental_Education_Level"].unique() #muestra todos los valores distintos
df_clean["Parental_Education_Level"].value_counts()  #reviso cuando hay de cada uno para ver si hay algo raro

df_clean.groupby("Parental_Education_Level")["Exam_Score"].mean().sort_values()

df.groupby("Parental_Education_Level")["Exam_Score"].mean().plot(kind="bar")
plt.title("Exam Score promedio según educación de los padres")
plt.xlabel("Nivel educativo de los padres")
plt.ylabel("Exam Score promedio")
plt.xticks(rotation=45)
plt.show()

df.boxplot(column="Exam_Score", by="Parental_Education_Level")
plt.title("Distribución de Exam Score por educación de los padres")
plt.suptitle("")
plt.xticks(rotation=45)
plt.show()

"""ANOVA"""

high = df_clean[df_clean["Parental_Education_Level"] == "High School"]["Exam_Score"]
college = df_clean[df_clean["Parental_Education_Level"] == "College"]["Exam_Score"]
post = df_clean[df_clean["Parental_Education_Level"] == "Postgraduate"]["Exam_Score"]

stats.f_oneway(high, college, post)

"""Al analizar el puntaje promedio según el nivel educativo de los padres, se observa una leve tendencia creciente desde High School (66.89) hasta Postgraduate (67.97). Sin embargo, la diferencia entre los grupos es reducida (aproximadamente 1 punto).

El boxplot muestra una alta superposición entre las distribuciones, con medianas y rangos intercuartílicos muy similares, lo que indica que el impacto práctico del nivel educativo parental es limitado.
Pero al aplicar un test ANOVA se obtiene un p-value < 0.05, lo que confirma que las diferencias observadas son estadísticamente significativas y no producto del azar.

En consecuencia, aunque el nivel educativo de los padres muestra una asociación con el rendimiento, su efecto es moderado y probablemente menor frente a variables como las horas de estudio, la asistencia o el desempeño previo.
"""

df_clean[["Hours_Studied","Exam_Score"]].corr()

plt.scatter(df_clean["Hours_Studied"], df_clean["Exam_Score"])
plt.xlabel("Hours Studied")
plt.ylabel("Exam Score")
plt.title("Hours Studied vs Exam Score")
plt.show()

"""El análisis entre las horas de estudio y el puntaje del examen muestra una correlación positiva moderada (r = 0.445). El scatter plot evidencia una tendencia ascendente: a medida que aumentan las horas dedicadas al estudio, el rendimiento promedio también se incrementa.

Si bien existe dispersión y casos particulares, el patrón general sugiere que las horas de estudio tienen un impacto más relevante sobre el desempeño académico que variables como el nivel educativo de los padres, cuyo efecto resultó estadísticamente significativo pero de baja magnitud práctica.
"""

df_clean[["Attendance", "Exam_Score"]].corr()

plt.scatter(df_clean["Attendance"], df_clean["Exam_Score"])
plt.xlabel("Attendance (%)")
plt.ylabel("Exam Score")
plt.title("Attendance vs Exam Score")
plt.show()

"""La relación entre la asistencia y el puntaje del examen presenta una correlación positiva moderada-alta (r = 0.58). El gráfico de dispersión evidencia una tendencia ascendente clara: los estudiantes con mayor porcentaje de asistencia suelen obtener mejores resultados académicos.

En comparación con otras variables analizadas, como las horas de estudio (r = 0.45) o el nivel educativo de los padres, la asistencia muestra un mayor poder explicativo sobre el rendimiento. Esto sugiere que la presencia regular en clase es un factor relevante para el desempeño académico, aunque no exclusivo, dado que aún existe dispersión entre los casos individuales.
"""

df_clean[["Previous_Scores", "Exam_Score"]].corr()

plt.scatter(df_clean["Previous_Scores"], df_clean["Exam_Score"])
plt.xlabel("Previous Scores")
plt.ylabel("Exam Score")
plt.title("Previous Scores vs Exam Score")
plt.show()

"""El desempeño previo presenta una correlación positiva débil con el puntaje del examen (r = 0.17). El bajo valor indica que las calificaciones anteriores explican solo una pequeña parte del rendimiento actual.

En comparación con variables como la asistencia (r = 0.58) o las horas de estudio (r = 0.45), el impacto de Previous_Scores resulta considerablemente menor en este conjunto de datos, sugiriendo que el rendimiento actual depende más del compromiso presente que del historial académico.
"""

df_clean[["Sleep_Hours", "Exam_Score"]].corr()

plt.scatter(df_clean["Sleep_Hours"], df_clean["Exam_Score"])
plt.xlabel("Sleep Hours")
plt.ylabel("Exam Score")
plt.title("Sleep Hours vs Exam Score")
plt.show()

"""El análisis entre las horas de sueño y el puntaje del examen arroja una correlación prácticamente nula (r = -0.017), lo que indica ausencia de relación lineal entre ambas variables.

En este conjunto de datos, el número de horas dormidas no muestra capacidad explicativa sobre el rendimiento académico, a diferencia de factores como la asistencia o las horas de estudio. Esto sugiere que el impacto del sueño podría estar oculto por el ruido del dataset o requerir un análisis no lineal para ser detectado.

# **Conclusión**

A partir del análisis exploratorio sobre el rendimiento académico (Exam_Score), se evaluó la relación con distintas variables explicativas.

Los resultados muestran que la asistencia a clases (Attendance) es el factor más influyente, con una correlación moderada-alta (r = 0.58). Los estudiantes con mayor presencia en clase tienden a obtener mejores resultados.

En segundo lugar, las horas de estudio (Hours_Studied) presentan una relación positiva moderada (r = 0.45), indicando que dedicar más tiempo al estudio mejora el rendimiento promedio, aunque con variabilidad entre individuos.

El nivel educativo de los padres (Parental_Education_Level) mostró diferencias estadísticamente significativas mediante ANOVA, pero con un impacto práctico reducido, ya que las distribuciones presentan alta superposición y diferencias promedio cercanas a un punto.

Por otro lado, el desempeño previo (Previous_Scores) evidenció una relación débil (r = 0.17), lo que sugiere que el rendimiento actual depende más del compromiso presente que del historial académico.

Finalmente, las horas de sueño (Sleep_Hours) no mostraron relación lineal con el puntaje del examen (r ≈ 0), indicando que, dentro de este dataset, no aportan capacidad explicativa relevante.

En conjunto, el análisis sugiere que los factores asociados al comportamiento actual del estudiante, especialmente la asistencia y el tiempo de estudio, tienen mayor impacto que las características familiares o históricas.

# **Modelo predictivo**
"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error

features = ["Attendance", "Hours_Studied", "Previous_Scores", "Sleep_Hours"]
X = df_clean[features]
y = df_clean["Exam_Score"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("R2:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))

"""El modelo de regresión lineal obtiene un coeficiente de determinación R² = 0.61, lo que indica que aproximadamente el 61% de la variabilidad del puntaje del examen es explicada por las variables incluidas en el modelo. Este resultado sugiere un buen desempeño predictivo para un modelo base, coherente con los hallazgos del análisis exploratorio.
El modelo presenta un error absoluto medio (MAE) de 1.38 puntos, lo que indica que, en promedio, las predicciones difieren del valor real del examen en poco más de un punto. Esto refleja una buena precisión para un modelo base de regresión lineal.
"""

pd.DataFrame({
    "Variable": features,
    "Coeficiente": model.coef_
}).sort_values(by="Coeficiente", ascending=False)

"""El análisis de los coeficientes del modelo de regresión lineal indica que las variables con mayor impacto en la predicción del rendimiento son las horas de estudio (coef. = 0.29) y la asistencia (coef. = 0.20). Esto sugiere que aumentar el tiempo dedicado al estudio y la presencia en clase mejora el puntaje esperado del examen.

El desempeño previo presenta un efecto reducido (coef. = 0.05), mientras que las horas de sueño no aportan señal relevante en el modelo (coef. ≈ 0), lo cual es coherente con los resultados observados durante el análisis exploratorio.
"""